const langData: Record<string, object> = {
  en: {
    lang: "English",
    title: "Tech Parallel Labs",
    slogan: "Simple and reliable technology partner",
    supplement: "",
    try: "Contact us!",
    whyTitle: "Why TPLabs?",
    whyContentTitleOne: "Technology",
    whyDescSloganOne: "",
    whyContentDescOne: "More than 10 years focus on distributed storage and developer technical services in the field of technical capabilities precipitation.",
    whyContentTitleTwo: "Data Security",
    whyDescSloganTwo: "",
    whyContentDescTwo: "Trust and support from more than 200 enterprise customers, Protect data security.",
    whyContentTitleThree: "Performance",
    whyDescSloganThree: "",
    whyContentDescThree: "Technical solutions with high throughput and low latency to quickly improve product performance.",
    solutionTitle: "Multi-Chain Solutions",
    solutionContentTitleOne: "Decentralized Storage",
    solutionContentDescOne: "The IPFS gateway, data retrieval services. The tools chain used for developers.",
    solutionContentTitleTwo: "Decentralized Computing Solutions",
    solutionContentDescTwo: "One-stop intelligent scene audio and video processing solution",
    solutionContentTitleThree: "Global IaaS",
    solutionContentDescThree: "Provide IT infrastructure capacity in more than 20 countries and regions around the world for rapid delivery.",
    customerTitle: "Our Customers",
    customerDesc: "Our goals are to provide the best services for customers from all over the world.",
    startTitle: "Getting Started",
    startStepOne: "Consultation",
    startDescOne: "We're ready for your business requirements,and features needs.",
    startStepTwo: "Preparation",
    startDescTwo: "If you contact our team, we will contact you ASAP.",
    startStepThree: "Perfect Solutions",
    startDescThree: "Though online meeting communication with each other, We will provider the best solutions to you.",
    startStepFour: "Launch!",
    startDescFour: "Your product is online!  We'll be by your side to help you get up and running.",
    infoTitleOne: "Support",
    infoContentHelp: "FAQ",
    infoTitleTwo: "Contact US",
    infoContentEmail: "Email",
    infoContentTwitter: "Twitter",
    faqContentTitleOne: "What is?",
    faqContentTextOne: "TPLabs is ..."
  },
  zh: {
    lang: "简体中文",
    title: "平行技术实验室",
    slogan: "简单可信赖的技术合作伙伴",
    supplement: "",
    try: "联系我们",
    whyTitle: "为什么选择TP Labs？",
    whyContentTitleOne: "技术服务",
    whyDescSloganOne: "",
    whyContentDescOne: "十多年专注于分布式存储和开发者技术服务领域的技术能力沉淀.",
    whyContentTitleTwo: "数据安全",
    whyDescSloganTwo: "",
    whyContentDescTwo: "来自200多家企业客户的信任和支持，保护数据安全.",
    whyContentTitleThree: "卓越性能",
    whyDescSloganThree: "",
    whyContentDescThree: "具有高吞吐量和低延迟的技术解决方案，以快速提升产品性能.",
    solutionTitle: "多链解决方案",
    solutionContentTitleOne: "分布式存储",
    solutionContentDescOne: "IPFS网关，数据检索服务。开发人员使用的工具链.",
    solutionContentTitleTwo: "去中心化计算服务",
    solutionContentDescTwo: "一站式的智能化场景音视频处理解决方案.",
    solutionContentTitleThree: "全球基础设施",
    solutionContentDescThree: "提供全球20多个国家与区域的 IT 基础建设能力,快速交付.",
    customerTitle: "客户分布",
    customerDesc: "我们的目标是为来自世界各地的客户提供最好的服务.",
    startTitle: "现在开始",
    startStepOne: "初步咨询",
    startDescOne: "我们已准备好满足您的业务需求和功能需求.",
    startStepTwo: "服务筹备",
    startDescTwo: "如果您联系我们的团队，我们会尽快与您联系.",
    startStepThree: "解决方案输出",
    startDescThree: "通过在线会议/拜访沟通，我们将为您提供最佳解决方案.",
    startStepFour: "发布上线!",
    startDescFour: "您的产品上线了！我们将在您身边帮助您启动和运行.",
    infoTitleOne: "帮助",
    infoContentHelp: "常见问题",
    infoTitleTwo: "联系我们",
    infoContentEmail: "邮箱",
    infoContentTwitter: "推特",
    faqContentTitleOne: "TPLabs 是什么？",
    faqContentTextOne: "TPLabs 提供哪些服务能力?"
  }
}

export default langData