const langData: Record<string, object> = {
  en: {
    lang: "English",
    title: "Tech Parallel Labs",
    slogan: "Simple and reliable technology partner",
    supplement: "",
    try: "Contact us!",
    whyTitle: "Why TPLabs?",
    whyContentTitleOne: "Technology",
    whyDescSloganOne: "",
    whyContentDescOne: "More than 10 years of technical capability accumulation.",
    whyContentTitleTwo: "Data Security",
    whyDescSloganTwo: "",
    whyContentDescTwo: "Trust and support from more than 200 enterprise customers, Protect data security.",
    whyContentTitleThree: "Performance",
    whyDescSloganThree: "",
    whyContentDescThree: "Technical solutions with high throughput and low latency to quickly improve product performance.",
    solutionTitle: "Multi-Chain Solutions",
    solutionContentTitleOne: "Decentralized Storage",
    solutionContentDescOne: "The IPFS gateway, data retrieval services. The tools chain used for developers.",
    solutionContentTitleTwo: "Decentralized Computing Solutions",
    solutionContentDescTwo: "One-stop scene audio and video processing",
    solutionContentTitleThree: "Global IaaS",
    solutionContentDescThree: "More than 20 global infrastructure service regions.",
    customerTitle: "Our Customers",
    customerDesc: "Our goals are to provide the best services for customers from all over the world.",
    startTitle: "Getting Started",
    startStepOne: "Consultation",
    startDescOne: "We're ready for your business requirements,and features needs.",
    startStepTwo: "Preparation",
    startDescTwo: "If you contact our team, we will contact you ASAP.",
    startStepThree: "Perfect Solutions",
    startDescThree: "Though online meeting communication with each other, We will provider the best solutions to you.",
    startStepFour: "Launch!",
    startDescFour: "Your product is online!  We'll be by your side to help you get up and running.",
    infoTitleOne: "Support",
    infoContentHelp: "FAQ",
    infoTitleTwo: "Contact US",
    infoContentEmail: "Email",
    infoContentTwitter: "Twitter",
    faqContentTitleOne: "What is?",
    faqContentTextOne: "TPLabs is ..."
  },
  zh: {
    lang: "简体中文",
    title: "平行技术实验室",
    slogan: "简单可信赖的技术合作伙伴",
    supplement: "",
    try: "联系我们",
    whyTitle: "为什么选择TP Labs？",
    whyContentTitleOne: "Technology",
    whyDescSloganOne: "whyDescSlogan",
    whyContentDescOne: "More than 10 years of technical capability accumulation.",
    whyContentTitleTwo: "Security",
    whyDescSloganTwo: "whyDescSloganTwo",
    whyContentDescTwo: "Trust and support from more than 200 enterprise customers, Protect data security.",
    whyContentTitleThree: "Performance",
    whyDescSloganThree: "whyDescSloganThree",
    whyContentDescThree: "Technical solutions with high throughput and low latency to quickly improve product performance.",
    solutionTitle: "Multi-Chain Solutions",
    solutionContentTitleOne: "Decentralized Storage",
    solutionContentDescOne: "The IPFS gateway, data retrieval services. The tools chain used for developers.",
    solutionContentTitleTwo: "Decentralized Computing Solutions",
    solutionContentDescTwo: "One-stop scene audio and video processing",
    solutionContentTitleThree: "Global IaaS",
    solutionContentDescThree: "More than 20 global infrastructure service regions.",
    customerTitle: "Our Customers",
    customerDesc: "Our goals are to provide the best services for customers from all over the world.",
    startTitle: "Getting Started",
    startStepOne: "Consultation",
    startDescOne: "We're ready for your business requirements,and features needs.",
    startStepTwo: "Preparation",
    startDescTwo: "If you contact our team, we will contact you ASAP.",
    startStepThree: "Perfect Solutions",
    startDescThree: "Though online meeting communication with each other, We will provider the best solutions to you.",
    startStepFour: "Launch!",
    startDescFour: "Your product is online!  We'll be by your side to help you get up and running.",
    infoTitleOne: "帮助",
    infoContentHelp: "常见问题",
    infoTitleTwo: "联系我们",
    infoContentEmail: "邮箱",
    infoContentTwitter: "推特",
    faqContentTitleOne: "What is?",
    faqContentTextOne: "TPLabs is ..."
  }
}

export default langData